version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "simple-sam-app"
s3_bucket = "matias-barrios-sam-test"
s3_prefix = "simple-sam-app"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

